# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [ 11, 17 ]  # (open)JDK releases
        exclude:  # to save time and resources
          - os: windows-latest
            jdk: 11
          - os: macOS-latest
            jdk: 11
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up openJDK version
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'zulu'
    - name: Install Dependencies
      run: npm install -g ro-crate-html-js
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build and Test with Gradle
      run: ./gradlew build
    - name: Do one Coveralls test report
      if: matrix.os == 'ubuntu-latest' && matrix.jdk == 17
      run: ./gradlew jacocoTestReport coveralls
